Don't use docs action as it is Docker based

diff --git a/.github/workflows/terraform-docs.yaml b/.github/workflows/terraform-docs.yaml
--- a/.github/workflows/terraform-docs.yaml
+++ b/.github/workflows/terraform-docs.yaml
@@ -13,8 +13,17 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
 
+      - name: Install terraform-docs
+        run: |
+          curl -Lo ./terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.17.0/terraform-docs-v0.17.0-$(uname)-amd64.tar.gz
+          tar -xzf terraform-docs.tar.gz
+          chmod +x terraform-docs
+          mv terraform-docs /usr/local/bin/terraform-docs
+
       - name: Generate Docs
-        uses: terraform-docs/gh-actions@v1.1.0
-        with:
-          fail-on-diff: true
-          recursive: true
+        run: |
+          terraform-docs . --recursive
+          if [ $(git_status) -ne 0 ]; then
+            echo "::error ::Uncommitted change(s) has been found!"
+            exit 1
+          fi
