Flatten PR to single file
Looks nicer in the UI

diff --git a/.github/workflows/terraform-pr-tests.yaml b/.github/workflows/terraform-pr-tests.yaml
--- a/.github/workflows/terraform-pr-tests.yaml
+++ b/.github/workflows/terraform-pr-tests.yaml
@@ -13,23 +13,163 @@ on:
     paths:
       - "**.tf"
 
+defaults:
+  run:
+    shell: bash
+    # working-directory: .
+
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
+
 jobs:
   docs:
     name: Terraform Docs
-    uses: SoliDeoGloria-Tech/workflow-testing/.github/workflows/terraform-docs.yaml@main
+    runs-on: [self-hosted, linux]
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Install terraform-docs
+        run: |
+          curl -Lo ./terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.17.0/terraform-docs-v0.17.0-$(uname)-amd64.tar.gz
+          tar -xzf terraform-docs.tar.gz
+          chmod +x terraform-docs
+          mv terraform-docs /usr/local/bin/terraform-docs
+
+      - name: Generate Docs
+        run: |
+          terraform-docs . --recursive
+          if [ $(git_status) -ne 0 ]; then
+            echo "::error ::Uncommitted change(s) has been found!"
+            exit 1
+          fi
+
   format:
     name: Terraform Format
-    uses: SoliDeoGloria-Tech/workflow-testing/.github/workflows/terraform-format.yaml@main
+    runs-on: [self-hosted, linux]
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v2 # v3 uses NodeJS 20
+
+      - name: Terraform Format
+        run: terraform fmt -check -recursive
+
   lint:
     name: Terraform Lint
-    uses: SoliDeoGloria-Tech/workflow-testing/.github/workflows/terraform-lint.yaml@main
+    runs-on: [self-hosted, linux]
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Setup tflint
+        uses: terraform-linters/setup-tflint@v4
+        with:
+          tflint_version: v0.51.1
+
+      - name: Run tflint
+        run: tflint --format compact --no-color --recursive
+
   validate:
     name: Terraform Validate
-    uses: SoliDeoGloria-Tech/workflow-testing/.github/workflows/terraform-validate.yaml@main
+    runs-on: [self-hosted, linux]
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v2 # v3 uses NodeJS 20
+
+      - name: Terraform Init
+        run: terraform init -backend=false
+
+      - name: Terraform Validate
+        id: validate
+        run: terraform validate -no-color
+
   plan:
     name: Terraform Plan
     needs:
       - format
       - validate
-    uses: SoliDeoGloria-Tech/workflow-testing/.github/workflows/terraform-plan.yaml@main
-    secrets: inherit
+    runs-on: [self-hosted, linux]
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v2 # v3 uses NodeJS 20
+
+      - name: Terraform Init
+        run: terraform init
+
+      - name: Terraform Plan
+        id: plan
+        run: terraform plan -no-color -out=tfplan
+        continue-on-error: true
+
+      - name: Terraform Show
+        id: show
+        run: terraform show -no-color tfplan
+
+      - name: Post Plan as Comment
+        uses: actions/github-script@v7
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            // 1. Retrieve existing bot comments for the PR
+            const { data: comments } = await github.rest.issues.listComments({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              issue_number: context.issue.number,
+            })
+            const botComment = comments.find(comment => {
+              return comment.user.type === 'Bot' && comment.body.includes('Terraform Plan')
+            })
+
+            // 2. Prepare format of the comment
+            const output = `#### Terraform Plan
+            \`\`\`\n
+            ${{ steps.show.outputs.stdout }}
+            \`\`\`
+            `;
+
+            // 3. If we have a comment, update it, otherwise create a new one
+            if (botComment) {
+              github.rest.issues.updateComment({
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                comment_id: botComment.id,
+                body: output
+              })
+            } else {
+              github.rest.issues.createComment({
+                issue_number: context.issue.number,
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                body: output
+              })
+            }
+
+      - name: Setup Infracost
+        if: env.INFRACOST_API_KEY
+        uses: infracost/actions/setup@v2
+        with:
+          api-key: ${{ secrets.INFRACOST_API_KEY }}
+          currency: AUD
+
+      - name: Add Infracost Details as Comment
+        if: env.INFRACOST_API_KEY
+        run: |
+          terraform show -json tfplan | tee ${{ runner.temp }}/plan.json
+          infracost breakdown --path ${{ runner.temp }}/plan.json \
+                              --format json \
+                              --out-file=${{ runner.temp }}/infracost.json
+          infracost comment github --path=${{ runner.temp }}/infracost.json \
+                                     --repo=${{ github.repository }} \
+                                     --github-token=${{ secrets.GITHUB_TOKEN }} \
+                                     --pull-request=${{ github.event.pull_request.number }} \
+                                     --behavior=update
